site_name: Detectium
site_url: https://nestorpons.github.io/detectium/site
nav:
    - Home: index.md
    - Legislacion: 
        - Ley de Seguridad Privada: legislacion/lsp.md
    - Jurisprudecia: 
        - Costas: juris/costas.md

theme: windmill